// <auto-generated />
using System;
using KonusarakOgrenCase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KonusarakOgrenCase.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20220411232855_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("KonusarakOgrenCase.Models.Exams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectAnswer1")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectAnswer2")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectAnswer3")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectAnswer4")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Essay")
                        .HasColumnType("TEXT");

                    b.Property<string>("Header")
                        .HasColumnType("TEXT");

                    b.Property<string>("Option1A")
                        .HasColumnType("TEXT");

                    b.Property<string>("Option1B")
                        .HasColumnType("TEXT");

                    b.Property<string>("Option1C")
                        .HasColumnType("TEXT");

                    b.Property<string>("Option1D")
                        .HasColumnType("TEXT");

                    b.Property<string>("Option2A")
                        .HasColumnType("TEXT");

                    b.Property<string>("Option2B")
                        .HasColumnType("TEXT");

                    b.Property<string>("Option2C")
                        .HasColumnType("TEXT");

                    b.Property<string>("Option2D")
                        .HasColumnType("TEXT");

                    b.Property<string>("Option3A")
                        .HasColumnType("TEXT");

                    b.Property<string>("Option3B")
                        .HasColumnType("TEXT");

                    b.Property<string>("Option3C")
                        .HasColumnType("TEXT");

                    b.Property<string>("Option3D")
                        .HasColumnType("TEXT");

                    b.Property<string>("Option4A")
                        .HasColumnType("TEXT");

                    b.Property<string>("Option4B")
                        .HasColumnType("TEXT");

                    b.Property<string>("Option4C")
                        .HasColumnType("TEXT");

                    b.Property<string>("Option4D")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title4")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exams");
                });
#pragma warning restore 612, 618
        }
    }
}
